---
- name: Nginx Certbot | Include nginx_repo.yml
  ansible.builtin.include_tasks: nginx_repo_{{ ansible_distribution | lower }}.yml
  when: nginx_certbot_repo is defined

- name: Nginx Certbot | Include nginx_install.yml
  ansible.builtin.include_tasks: nginx_install.yml

- name: Nginx Certbot | Include sync_cert.yml
  ansible.builtin.include_tasks: sync_cert.yml
  when: nginx_certbot_share_cert is defined

- name: Nginx Certbot | Include certbot_install.yml
  ansible.builtin.include_tasks: certbot_install.yml

- name: Nginx Certbot | Include nginx_quic.yml
  ansible.builtin.include_tasks: nginx_quic.yml
  when: nginx_certbot_quic is true

- name: Nginx Certbot | Include nginx_load_ssl.yml
  ansible.builtin.include_tasks: nginx_load_ssl.yml

- name: Nginx Certbot | Include nginx_stream.yml
  ansible.builtin.include_tasks: nginx_stream.yml
  when: nginx_certbot_custom_stream_block is defined
