---
- name: Nginx Stream | Add stream block configuration
  ansible.builtin.blockinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: '^#mail {'
    block: |
      stream {
        include /etc/nginx/conf.d/*.stream;
        include /etc/nginx/conf.d/resolver.conf;
      }
  notify: Reload nginx

- name: Nginx Stream | Copy nginx stream configuration
  ansible.builtin.template:
    src: "templates/nginx_conf.d/custom_stream.j2"
    dest: "/etc/nginx/conf.d/{{ nginx_certbot_stream_name }}.stream"
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx
