---

- name: Nginx | Install Nginx
  package:
    name: nginx
    state: latest

- name: Nginx | Copy nginx conf for certbot init to sites-available
  template:
    src: templates/nginx_cerbot_init.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
