---
- name: Nginx | Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Nginx | Install Nginx-full
  ansible.builtin.package:
    name: nginx-full
    state: present
  when: nginx_certbot_custom_stream_block is defined
