---
- name: Nginx SSL | Copy conf snippet with strong ssl settings
  ansible.builtin.template:
    src: files/ssl-params.conf
    dest: /etc/nginx/snippets/ssl-params.conf
    owner: root
    group: root
    mode: "0644"

- name: Nginx SSL | Generate strong Diffie-Hellman parameters (may take a few minutes)
  community.crypto.openssl_dhparam:
    path: /etc/ssl/certs/dhparam.pem
    size: 4096
  async: "{{ nginx_cerbot_dh_timeout }}"
  poll: 0      # Do not wait for the task to complete
  register: long_running_task

- name: Nginx SSL | Check on the long-running task
  ansible.builtin.async_status:
    jid: "{{ long_running_task.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: "{{ (nginx_cerbot_dh_timeout / 30) | int }}"
  delay: 30

- name: Nginx SSL | Create nginx conf directory
  ansible.builtin.file:
    path: "/etc/nginx/conf.d/{{ nginx_certbot_domain_name }}.d"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Nginx SSL | Copy nginx conf to sites-available
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - {
      src: "templates/nginx_conf.d/README.j2",
      dest: "/etc/nginx/conf.d/{{ nginx_certbot_domain_name }}.d/README",
    }
    - {
      src: "templates/nginx_conf.d/{{ nginx_certbot_app.http_template_name }}.j2",
      dest: "/etc/nginx/conf.d/{{ nginx_certbot_domain_name }}.d/{{ nginx_certbot_app.name }}.conf",
    }
    - {
      src: "templates/nginx_conf.d/{{ nginx_certbot_app.upstream_template_name }}.j2",
      dest: "/etc/nginx/conf.d/{{ nginx_certbot_domain_name }}.d/{{ nginx_certbot_app.name }}.upstream",
    }
  notify: Reload nginx

- name: Nginx SSL | Copy nginx reverse proxy base conf
  ansible.builtin.template:
    src: "templates/nginx_reverse_proxy.j2"
    dest: "/etc/nginx/conf.d/{{ nginx_certbot_domain_name }}.conf"
    owner: root
    group: root
    mode: "0644"
  when: nginx_certbot_ha is undefined and nginx_certbot_quic is false
  notify: Reload nginx

- name: Nginx SSL | Copy nginx reverse proxy HA base conf
  ansible.builtin.template:
    src: "templates/nginx_reverse_proxy_ha.j2"
    dest: "/etc/nginx/conf.d/{{ nginx_certbot_domain_name }}.conf"
    owner: root
    group: root
    mode: "0644"
  when: nginx_certbot_ha is defined
  notify: Reload nginx

- name: Nginx SSL | Copy nginx reverse proxy base conf for http3
  ansible.builtin.template:
    src: "templates/nginx_reverse_proxy_quic.j2"
    dest: "/etc/nginx/conf.d/{{ nginx_certbot_domain_name }}.conf"
    owner: root
    group: root
    mode: "0644"
  when: nginx_certbot_quic is true
  notify: Reload nginx
