---
- name: Nginx SSL | Copy conf snippet with strong ssl settings
  template:
    src: files/ssl-params.conf
    dest: /etc/nginx/snippets/ssl-params.conf
    owner: root
    group: root
    mode: 0644

- name: Nginx SSL | Generate strong Diffie-Hellman parameters (may take a few minutes)
  tags: notest
  community.crypto.openssl_dhparam:
    path: /etc/ssl/certs/dhparam.pem
    size: 4096


- name: Nginx SSL | Create conf.d subdirectories
  ansible.builtin.file:
    path: "/etc/nginx/conf.d/{{ nginx_certbot_domain_name }}.d/"
    state: directory
    owner: root
    group: root
    mode: 0755    

- name: Nginx SSL | Copy nginx configurations
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: "templates/nginx_conf.d/README.j2", dest: "/etc/nginx/conf.d/{{ nginx_certbot_domain_name }}.d/README" }
    - { src: "templates/nginx_conf.d/{{ nginx_certbot_app.template_name }}.j2", dest: "/etc/nginx/conf.d/{{ nginx_certbot_domain_name }}.d/{{ nginx_certbot_app.template_name }}.conf" }
    - { src: "templates/nginx_reverse_proxy.j2", dest: "/etc/nginx/conf.d/{{ nginx_certbot_domain_name }}.conf" }
  notify: reload nginx
