---
- name: Check if nginx syntax is good
  ansible.builtin.command: nginx -t
  register: result
  changed_when: result.rc != 0
  when: molecule_yml is not defined
  listen: Reload nginx

- name: Reload nginx if conf is ok
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  when: molecule_yml is not defined and result
  listen: Reload nginx

- name: Reload sshd
  ansible.builtin.systemd:
    name: sshd
    state: reloaded
  when: molecule_yml is not defined

- name: Sync cert
  ansible.builtin.command: >-
    /etc/letsencrypt/renewal-hooks/deploy/sync-certificates.sh
  register: output
  changed_when: output.rc != 0
  when: nginx_certbot_share_cert.state | default('') == 'master'
