---
- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  when: molecule_yml is not defined

- name: Reload sshd
  ansible.builtin.systemd:
    name: sshd
    state: reloaded
  when: molecule_yml is not defined

- name: Sync cert
  ansible.builtin.command: >-
    /etc/letsencrypt/renewal-hooks/deploy/sync-certificates.sh
  register: output
  changed_when: output.rc != 0
  when: nginx_certbot_share_cert.state | default('') == 'master'
